[profile.default]
solc_version = "0.8.23" # Override for the solc version (setting this ignores `auto_detect_solc`)
evm_version = "paris" # to prevent usage of PUSH0, which is not supported on all chains
libraries = []
optimizer = true
optimizer_runs = 200
verbosity = 0
ffi = true
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
out = "out"
script = "script"
src = "src"
test = "test"
auto_detect_remappings = false
assertions_revert = false # see https://t.me/foundry_rs/36706
legacy_assertions = true # see https://t.me/foundry_rs/36706
gas_limit = "18446744073709551615" # see https://t.me/foundry_rs/36706
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/tokenized-strategy/lib/openzeppelin-contracts/',
    'openzeppelin-contracts/contracts=lib/tokenized-strategy/lib/openzeppelin-contracts/contracts',
    'tokenized-strategy=lib/tokenized-strategy/src/',
    'superform-core=lib/superform-core/src/',
    'ERC1155A=lib/superform-core/lib/ERC1155A/src/',
]


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
